export const AREA_LIST_REQUEST = 'AREA_LIST_REQUEST';
export const AREA_LIST_SUCCESS = 'AREA_LIST_SUCCESS';
export const AREA_LIST_FAIL = 'AREA_LIST_FAIL';

export const AREA_ADD_REQUEST = 'AREA_ADD_REQUEST';
export const AREA_ADD_SUCCESS = 'AREA_ADD_SUCCESS';
export const AREA_ADD_FAIL = 'AREA_ADD_FAIL';

export const AREA_EDIT_REQUEST = 'AREA_EDIT_REQUEST';
export const AREA_EDIT_SUCCESS = 'AREA_EDIT_SUCCESS';
export const AREA_EDIT_FAIL = 'AREA_EDIT_FAIL';

export const AREA_DELETE_REQUEST = 'AREA_DELETE_REQUEST';
export const AREA_DELETE_SUCCESS = 'AREA_DELETE_SUCCESS';
export const AREA_DELETE_FAIL = 'AREA_EDIT_FAIL';
