export const REGULATE_ITEM_LIST_REQUEST = 'REGULATE_ITEM_LIST_REQUEST';
export const REGULATE_ITEM_LIST_SUCCESS = 'REGULATE_ITEM_LIST_SUCCESS';
export const REGULATE_ITEM_LIST_FAIL = 'REGULATE_ITEM_LIST_FAIL';

