export const UNIT_LIST_REQUEST = 'UNIT_LIST_REQUEST';
export const UNIT_LIST_SUCCESS = 'UNIT_LIST_SUCCESS';
export const UNIT_LIST_FAIL = 'UNIT_LIST_FAIL';

export const UNIT_ADD_REQUEST = 'UNIT_ADD_REQUEST';
export const UNIT_ADD_SUCCESS = 'UNIT_ADD_SUCCESS';
export const UNIT_ADD_FAIL = 'UNIT_ADD_FAIL';

export const UNIT_EDIT_REQUEST = 'UNIT_EDIT_REQUEST';
export const UNIT_EDIT_SUCCESS = 'UNIT_EDIT_SUCCESS';
export const UNIT_EDIT_FAIL = 'UNIT_EDIT_FAIL';

export const UNIT_DELETE_REQUEST = 'UNIT_DELETE_REQUEST';
export const UNIT_DELETE_SUCCESS = 'UNIT_DELETE_SUCCESS';
export const UNIT_DELETE_FAIL = 'UNIT_EDIT_FAIL';
